class ESTUDIANTES {
  constructor(CODIGO, NOMBRE, APELLIDOS, SEMESTRE, CARRERA, COD_ASIGNATURA) {
    this.CODIGO = CODIGO;
    this.NOMBRE = NOMBRE;
    this.APELLIDOS = APELLIDOS;
    this.SEMESTRE = SEMESTRE;
    this.CARRERA = CARRERA;
    this.COD_ASIGNATURA = COD_ASIGNATURA;
  }
}
export default ESTUDIANTES;
